"""Initial tables

Revision ID: 50a2eb0b4f7b
Revises: 
Create Date: 2026-03-10 00:55:47.621195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50a2eb0b4f7b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brief', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('project_type', sa.Enum('WEB_SIMPLE', 'WEB_COMPLEX', name='projecttype'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'INTAKE', 'RESEARCH', 'ARCHITECT', 'DESIGN', 'CODE_GENERATION', 'QA', 'DEPLOYMENT', 'COMPLETED', 'FAILED', 'PAUSED', 'CANCELLED', name='projectstatus'), nullable=False),
    sa.Column('cost_estimate', sa.Float(), nullable=True),
    sa.Column('cost_profile', sa.Enum('BUDGET', 'BALANCED', 'PREMIUM', name='costprofile'), nullable=False),
    sa.Column('github_repo', sa.String(length=500), nullable=True),
    sa.Column('live_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('agent_outputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('project_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('revision_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_project_created_at', 'projects', ['created_at'], unique=False)
    op.create_index('idx_project_status', 'projects', ['status'], unique=False)
    op.create_index('idx_project_type', 'projects', ['project_type'], unique=False)
    op.create_table('agent_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('agent_step', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_log_agent_name', 'agent_logs', ['agent_name'], unique=False)
    op.create_index('idx_agent_log_model', 'agent_logs', ['model_used'], unique=False)
    op.create_index('idx_agent_log_project_id', 'agent_logs', ['project_id'], unique=False)
    op.create_index('idx_agent_log_timestamp', 'agent_logs', ['timestamp'], unique=False)
    op.create_table('cost_tracking',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cost_tracking_project_id', 'cost_tracking', ['project_id'], unique=False)
    op.create_index('idx_cost_tracking_timestamp', 'cost_tracking', ['timestamp'], unique=False)
    op.create_table('deployment_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('VERCEL', 'RAILWAY', 'SUPABASE', 'GITHUB_PAGES', 'NETLIFY', 'MANUAL', name='deploymentplatform'), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'SUCCESS', 'FAILED', 'ROLLED_BACK', name='deploymentstatus'), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('commit_sha', sa.String(length=40), nullable=True),
    sa.Column('deployed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deployment_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_deployment_deployed_at', 'deployment_records', ['deployed_at'], unique=False)
    op.create_index('idx_deployment_platform', 'deployment_records', ['platform'], unique=False)
    op.create_index('idx_deployment_project_id', 'deployment_records', ['project_id'], unique=False)
    op.create_index('idx_deployment_status', 'deployment_records', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_deployment_status', table_name='deployment_records')
    op.drop_index('idx_deployment_project_id', table_name='deployment_records')
    op.drop_index('idx_deployment_platform', table_name='deployment_records')
    op.drop_index('idx_deployment_deployed_at', table_name='deployment_records')
    op.drop_table('deployment_records')
    op.drop_index('idx_cost_tracking_timestamp', table_name='cost_tracking')
    op.drop_index('idx_cost_tracking_project_id', table_name='cost_tracking')
    op.drop_table('cost_tracking')
    op.drop_index('idx_agent_log_timestamp', table_name='agent_logs')
    op.drop_index('idx_agent_log_project_id', table_name='agent_logs')
    op.drop_index('idx_agent_log_model', table_name='agent_logs')
    op.drop_index('idx_agent_log_agent_name', table_name='agent_logs')
    op.drop_table('agent_logs')
    op.drop_index('idx_project_type', table_name='projects')
    op.drop_index('idx_project_status', table_name='projects')
    op.drop_index('idx_project_created_at', table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
