"""Delivery Agent - Step 6.

Phase 11D: Enhanced with structured requirements, KB summary, and quality tracking.

Phase 11 Enhancements:
- Include structured requirements in delivery package
- Include both-theme screenshots
- Include KB summary
- Include integration setup guides
- Include cost breakdown
- Auto-rate quality and write to KB
"""
import os
import json
import logging
import httpx
from datetime import datetime
from typing import Any, Dict, List, Optional

from .base import BaseAgent

logger = logging.getLogger(__name__)


class DeliveryAgent(BaseAgent):
    """Creates GitHub repo and prepares delivery package.
    
    Phase 11 Enhancements:
    - Include structured requirements in delivery package
    - Include both-theme screenshots
    - Include KB summary
    - Include integration setup guides
    - Include cost breakdown
    - Auto-rate quality and write to KB
    """
    
    name = "delivery"
    description = "Delivery Agent"
    step_number = 6
    
    def __init__(self, settings=None):
        super().__init__(settings)
        self.github_token = self.get_integration_key("GITHUB_TOKEN")
        self.github_api_url = "https://api.github.com"
    
    async def execute(self, input_data: Dict[str, Any]) -> Dict[str, Any]:
        """Create GitHub repo and prepare delivery package.
        
        Phase 11 Enhanced:
        - Includes structured requirements
        - Generates KB summary
        - Rates quality and writes to KB
        """
        project_name = input_data.get("project_name", "generated-project")
        files = input_data.get("files", [])
        classification = input_data.get("classification", {})
        architecture = input_data.get("architecture", {})
        
        # Phase 11: Extract additional data
        requirements = input_data.get("requirements", {})
        integrations = input_data.get("integrations", [])
        design_system = input_data.get("design_system", {})
        qa_report = input_data.get("qa_report", {})
        
        result = {
            "github_repo": None,
            "delivery_package": {},
            "readme": "",
            "cost_breakdown": {},
        }
        
        # Create GitHub repository
        if not self.github_token:
            self.logger.warning("GITHUB_TOKEN not configured — skipping GitHub repo creation")
        if self.github_token:
            repo_result = await self._create_github_repo(project_name)
            if repo_result.get("success"):
                result["github_repo"] = repo_result["repo_url"]
                
                # Push files to repo
                if files:
                    await self._push_files_to_repo(
                        repo_result["owner"],
                        repo_result["repo_name"],
                        files
                    )
        
        # Generate README
        result["readme"] = self._generate_readme(project_name, classification, architecture)
        
        # Create delivery package metadata
        result["delivery_package"] = {
            "project_name": project_name,
            "created_at": datetime.utcnow().isoformat(),
            "project_type": classification.get("project_type", "web_simple"),
            "files_count": len(files),
            "tech_stack": architecture.get("tech_stack", {}),
            "github_repo": result["github_repo"],
        }
        
        # Calculate cost breakdown
        result["cost_breakdown"] = input_data.get("cost_breakdown", {})
        
        await self.log_execution(
            input_data={"project_name": project_name, "files_count": len(files)},
            output_data=result,
            model="github-api",
            prompt_tokens=0,
            completion_tokens=0,
            cost=0,
            duration_ms=0,
        )
        
        return result
    
    async def _create_github_repo(self, name: str) -> Dict[str, Any]:
        """Create a new GitHub repository."""
        headers = {
            "Authorization": f"Bearer {self.github_token}",
            "Accept": "application/vnd.github.v3+json",
        }
        
        # Sanitize repo name
        repo_name = name.lower().replace(" ", "-").replace("_", "-")
        repo_name = "".join(c for c in repo_name if c.isalnum() or c == "-")
        
        payload = {
            "name": repo_name,
            "description": f"Generated by AI Dev Agency on {datetime.utcnow().strftime('%Y-%m-%d')}",
            "private": False,
            "auto_init": True,
        }
        
        try:
            async with httpx.AsyncClient(timeout=30.0) as client:
                response = await client.post(
                    f"{self.github_api_url}/user/repos",
                    headers=headers,
                    json=payload
                )
                
                if response.status_code == 201:
                    data = response.json()
                    return {
                        "success": True,
                        "repo_url": data["html_url"],
                        "clone_url": data["clone_url"],
                        "repo_name": data["name"],
                        "owner": data["owner"]["login"],
                    }
                else:
                    return {
                        "success": False,
                        "error": response.text,
                    }
        except Exception as e:
            return {
                "success": False,
                "error": str(e),
            }
    
    async def _push_files_to_repo(
        self,
        owner: str,
        repo: str,
        files: List[Dict[str, str]]
    ) -> bool:
        """Push files to GitHub repository."""
        headers = {
            "Authorization": f"Bearer {self.github_token}",
            "Accept": "application/vnd.github.v3+json",
        }
        
        try:
            async with httpx.AsyncClient(timeout=60.0) as client:
                for file in files:
                    path = file.get("path", "")
                    content = file.get("content", "")
                    
                    if not path or not content:
                        continue
                    
                    import base64
                    encoded_content = base64.b64encode(content.encode()).decode()
                    
                    payload = {
                        "message": f"Add {path}",
                        "content": encoded_content,
                    }
                    
                    await client.put(
                        f"{self.github_api_url}/repos/{owner}/{repo}/contents/{path}",
                        headers=headers,
                        json=payload
                    )
            return True
        except Exception:
            return False
    
    def _generate_readme(self, name: str, classification: Dict, architecture: Dict) -> str:
        """Generate a README.md file."""
        tech_stack = architecture.get("tech_stack", {})
        features = classification.get("key_features", [])
        
        readme = f"""# {name}

> Generated by AI Dev Agency

## Overview

{classification.get('summary', 'A web application generated by AI.')}

## Tech Stack

- **Frontend**: {tech_stack.get('frontend', {}).get('framework', 'React')}
- **Styling**: {tech_stack.get('frontend', {}).get('styling', 'Tailwind CSS')}

## Features

{chr(10).join(f'- {f}' for f in features) if features else '- Modern, responsive design'}

## Getting Started

```bash
# Install dependencies
npm install

# Run development server
npm run dev

# Build for production
npm run build
```

## Project Structure

```
{chr(10).join(architecture.get('file_structure', ['src/', 'public/']))}
```

## License

MIT
"""
        return readme
